#!/bin/bash

docker rm -f httpd
docker rm -f nginx
docker rm -f datacontainer

#----APACHE-----
docker create -v `pwd`:/data/www/html --name httpd -p 8080:80 nandrade/httpd-php

#----NGINX-----
docker create -v `pwd`:/data/www/html --name nginx -p 8081:80 nginx

#----CONTENIDOR-DOBLE-VOLUM-----
docker run -d --volumes-from httpd --volumes-from nginx --name datacontainer ubuntu

#----ARRANCAR-CONTENIDORS-----
docker start httpd
docker start nginx
echo "DATACONTAINER PONIENDOSE EN SEGUNDO PLANO"
docker start datacontainer

