#!/bin/bash
docker rm -f mariadb
docker rm -f moodle
docker rm -f datacontainer

#---MARIADB----
docker run -d --name mariadb \
 -e ALLOW_EMPTY_PASSWORD=yes \
 -e MARIADB_USER=bn_moodle \
 -e MARIADB_DATABASE=bitnami_moodle \
 -v /path/to/mariadb-persistence:/bitnami \
 bitnami/mariadb:latest

#---MOODLE----
docker run -d -p 8080:80 -p 443:443 --name moodle \
 -e ALLOW_EMPTY_PASSWORD=yes \
 -e MOODLE_DATABASE_USER=bn_moodle \
 -e MOODLE_DATABASE_NAME=bitnami_moodle \
 --volume /path/to/moodle-persistence:/bitnami \
 bitnami/moodle:latest


#----CONTENIDOR-DOBLE-VOLUM-----
docker run -d --volumes-from mariadb --volumes-from moodle --name datacontainer ubuntu

#----ARRANCAR-CONTENIDORS-----
echo "DATACONTAINER PONIENDOSE EN SEGUNDO PLANO"
docker start mariadb
docker start moodle
docker start datacontainer

